[package]
name = "invis-engine"
version = "0.1.0"
description = "Windows workspace that is invisible to screen capture"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-global-shortcut = "2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
